const projectData = [
  {
    title: "Travel Agency Website",
    image: "https://i.ibb.co.com/jJ3n3mv/go-tripe.jpg",
    description: "Static Website for Travel Agency Beautiful, Full Responsive, Multipage…",
    liveLink: "https://devmdmainuddin.github.io/go-trip/",
    clientLink: "https://github.com/Devmdmainuddin/go-trip",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T09:42:08.935Z",
  },
  {
    title: "Static Website for Hockey Club",
    image: "https://i.ibb.co.com/f4qqsmn/hockeys.jpg",
    description:
      "This Hockey Club static website is built to highlight the club’s activities and events.",
    liveLink: "https://devmdmainuddin.github.io/Hockey/",
    clientLink: "https://github.com/Devmdmainuddin/Hockey",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T09:54:09.748Z",
  },
  {
    title: "Bus Reservation System",
    image: "https://i.ibb.co.com/Mk87MrC/bus-tricket.jpg",
    description:
      "Bus reservation system is an essential transport software for managing ticket bookings efficiently.",
    liveLink: "https://devmdmainuddin.github.io/e-ticket/",
    clientLink: "https://github.com/Devmdmainuddin/e-ticket",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T10:04:42.227Z",
  },
  {
    title: "Recipe Calories Calculator Website",
    image: "https://i.ibb.co.com/L0XX7h5/recipy.jpg",
    description:
      "The Recipe Calories Calculator is a user-friendly tool designed to help users estimate the nutritional value of their recipes.",
    liveLink: "https://flavor-recipe.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/recipes",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T13:19:58.636Z",
  },
  {
    title: "Bookshelf Website",
    image: "https://i.ibb.co.com/3C7qvkG/book.jpg",
    description:
      "The Bookshelf Website is a digital platform designed for book lovers to explore, organize, and share their favorite reads.",
    liveLink: "http://unable-sink.surge.sh/",
    clientLink: "https://github.com/Devmdmainuddin/book-stores",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T13:35:45.448Z",
  },
  {
    title: "Properties for Rent and Sell Website",
    image: "https://i.ibb.co.com/j4Z7Py9/property.jpg",
    description:
      "In the digital age, a robust online presence is essential for any real estate business. This website offers a seamless platform for showcasing properties available for rent and sale.",
    liveLink: "https://luxury-properties-a2a28.web.app/",
    clientLink: "https://github.com/Devmdmainuddin/luxury-properties",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T13:47:05.882Z",
  },
  {
    title: "Art & Craft Store",
    image: "https://i.ibb.co.com/0QJP98s/art.jpg",
    description:
      "Art & Craft Store allows users to post their art and crafts for selling, update their posts, and manage their items efficiently.",
    liveLink: "https://brush-tech-artisty.web.app/",
    clientLink: "https://github.com/Devmdmainuddin/Brush-tech-artisty",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T13:53:02.331Z",
  },
  {
    title: "Reservations Booking Website",
    image: "https://i.ibb.co.com/HG50JXw/garej.jpg",
    description:
      "A Reservations Booking Website is a platform designed to facilitate users in seamlessly booking reservations for various services.",
    liveLink: "https://gericht-43db4.web.app/",
    clientLink: "https://github.com/Devmdmainuddin/Gericht",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T13:58:13.736Z",
  },
  {
    title: "Alternative Product Information System",
    image: "https://i.ibb.co.com/rvs5VwN/shop.jpg",
    description:
      "Alternative Product Information System provides a single view platform for exploring and managing alternative products efficiently.",
    liveLink: "https://suggestforgoods.firebaseapp.com/",
    clientLink: "https://github.com/Devmdmainuddin/ShoppingSwiftly",
    serverLink: "https://github.com/Devmdmainuddin/shopswiftly-server",
    tags: [],
    createAt: "2024-10-24T14:04:47.774Z",
  },
  {
    title: "Full-functionality eCommerce website using React and Redux RTK, Express",
    image: "https://i.ibb.co.com/j3MGQzk/ecom.jpg",
    description:
      "This website includes key features like product listing, filtering, adding to cart, user authentication, and order management.",
    liveLink: "https://shopfusion-sf.web.app/",
    clientLink: "https://github.com/Devmdmainuddin/shopFusion",
    serverLink: "https://github.com/Devmdmainuddin/shopFusion-server",
    tags: [],
    createAt: "2024-10-24T14:11:50.940Z",
  },
  {
    title: "Complete eCommerce project",
    image: "https://i.ibb.co.com/8c40xMb/trandy.jpg",
    description:
      "This e-commerce project is a complete and scalable online shopping platform with features like product listings, cart functionality, user authentication, and payment integration.",
    liveLink: "https://trendymart-tm.web.app/",
    clientLink: "https://github.com/Devmdmainuddin/trendyMart",
    serverLink: "https://github.com/Devmdmainuddin/trendyMart-server",
    tags: [],
    createAt: "2024-10-24T14:46:50.951Z",
  },
  {
    title: "Blog Website",
    image: "https://i.ibb.co.com/HnctRPx/blogy.jpg",
    description:
      "This blogging platform allows users to create, read, update, and delete blog posts. It includes authentication, user management, and a clean, user-friendly interface.",
    liveLink: "https://blogy-2.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/blogy",
    serverLink: "https://github.com/Devmdmainuddin/blogy-server",
    tags: [],
    createAt: "2024-10-24T14:58:50.855Z",
  },
  {
    title: "Chat Application",
    image: "https://i.ibb.co.com/z5R1sqF/ch.jpg",
    description:
      "This real-time chat application allows users to communicate instantly with support for one-on-one and group conversations.",
    liveLink: "https://chitchatly-chattingapp.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/chitchatly",
    serverLink: "",
    tags: [],
    createAt: "2024-10-24T15:44:16.467Z",
  },
  {
    title: "React Ecommerce Website",
    image: "https://i.ibb.co.com/MfXkD6C/res.jpg",
    description:
      "Building a feature-rich eCommerce application in React, with Firebase integration for authentication and real-time data.",
    liveLink: "https://tech-store-ts.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/tech-store",
    serverLink: "",
    tags: [],
    createAt: "2024-10-25T16:23:14.844Z",
  },
  {
    title: "HTML Ecommerce Website",
    image: "https://i.ibb.co.com/Zh0ZHRv/bbb.jpg",
    description: "Responsive eCommerce website built with HTML, Tailwind CSS, and JavaScript.",
    liveLink: "https://devmdmainuddin.github.io/e-shop/",
    clientLink: "https://github.com/Devmdmainuddin/e-shop",
    serverLink: "",
    tags: [],
    createAt: "2024-10-25T16:49:06.303Z",
  },
  {
    title: "Cleaning Services Agency",
    image: "https://i.ibb.co.com/pykf5qL/cliene.jpg",
    description:
      "Creating a landing page for a cleaning services agency in React.js can help businesses showcase their services and attract potential clients.",
    liveLink: "https://cleaning-services-agency.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/cleaning-services",
    serverLink: "",
    tags: [],
    createAt: "2024-11-08T03:36:12.108Z",
  },
  {
    title: "Clean Your House - Agency Website",
    image: "https://i.ibb.co.com/jJLT7QH/cleaning-services-agency.jpg",
    description: "Website landing page design with React and Tailwind.",
    liveLink: "https://cleaning-services-agency.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/cleaning-services",
    serverLink: "",
    tags: [],
    createAt: "2024-11-10T10:37:33.509Z",
  },
  {
    title: "E-Learning Online Educational Website",
    image: "https://i.ibb.co.com/Vq9zh25/Screenshot-2024-11-10-102251.png",
    description: "Educational website landing page design with React and Tailwind.",
    liveLink: "https://edex-e-learning.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/E-learning-eDex",
    serverLink: "",
    tags: [],
    createAt: "2024-11-10T10:39:18.810Z",
  },
  {
    title: "comforty-ecommerce-shop",
    image: "https://i.ibb.co.com/jTWPwYC/Screenshot-12-11-2024-164241-comforty-eco…",
    description:
      "This is a fully responsive e-commerce shopping website project built using React and other modern technologies.",
    liveLink: "https://comforty-ecommerce-shop.netlify.app/",
    clientLink: "https://github.com/Devmdmainuddin/Comforty-Ecommerce",
    serverLink: "",
    tags: [],
    createAt: "2024-11-12T10:43:35.637Z",
  },
];
export default projectData