import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/providers/theme-provider";
import Navbar from "@/components/shared/Navbar";
import Link from "next/link";
import {
  Facebook,
  Github,
  Instagram,
  Linkedin,
  MessageSquareText,
  TvMinimalPlay,
  UserRound,
} from "lucide-react";
import {HomeIcon, ScrollText} from "lucide-react";
import {Dock, DockIcon, DockItem, DockLabel} from "@/components/ui/dock";
import Footer from "@/components/shared/Footer";
import ThemeSwitcher from "@/components/shared/ThemeSwitcher";

const data = [
  {
    title: "Home",
    icon: <HomeIcon className="h-full w-full text-neutral-600 dark:text-neutral-300" />,
    href: "/",
  },
  {
    title: "About",
    icon: <UserRound className="h-full w-full text-neutral-600 dark:text-neutral-300" />,
    href: "about#",
  },
  {
    title: "Services",
    icon: <TvMinimalPlay className="h-full w-full text-neutral-600 dark:text-neutral-300" />,
    href: "services",
  },
  {
    title: "Contact",
    icon: <MessageSquareText className="h-full w-full text-neutral-600 dark:text-neutral-300" />,
    href: "contact",
  },
  {
    title: "Blog",
    icon: <ScrollText className="h-full w-full text-neutral-600 dark:text-neutral-300" />,
    href: "blog",
  },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
          <Footer />

          <div className=" flex flex-col fixed top-[40%] left-0  ">
            <li
              className={
                "flex justify-center items-center w-[180px]  bg-[#e6e9ebfc] text-sm py-2 px-4 text-white rounded-tr-md rounded-br-md  ml-[-132px] hover:ml-0 transition-all duration-300"
              }
            >
              <Link
                href="https://www.facebook.com/profile.php?id=100006959283779"
                className="flex justify-between items-center w-full text-[#03a9f4]"
              >
                Facebook <Facebook size={22} className="secleup" />
              </Link>
            </li>
            <li
              className={
                "flex justify-center items-center w-[180px] bg-[#e6e9ebfc] text-sm py-2 px-4 rounded-tr-md rounded-br-md text-[#fe0761] ml-[-132px] hover:ml-0 transition-all duration-300"
              }
            >
              <Link href="" className="flex justify-between items-center w-full">
                Instagram <Instagram size={22} className="secleup" />{" "}
              </Link>
            </li>
            <li
              className={
                "flex justify-center items-center w-[180px]  bg-[#e6e9ebfb] text-sm py-2 px-4 text-[#27ace0] rounded-tr-md rounded-br-md  ml-[-132px] hover:ml-0 transition-all duration-300"
              }
            >
              <Link
                href="https://www.linkedin.com/in/devmainuddin/"
                className="flex justify-between items-center w-full"
              >
                {" "}
                LinkedinIn <Linkedin size={22} className="secleup" />{" "}
              </Link>
            </li>
            <li
              className={
                "flex justify-center items-center w-[180px]  bg-[#e8e8e8]  text-sm py-2 px-4 text-[#1f2328] rounded-tr-md rounded-br-md  ml-[-132px] hover:ml-0 transition-all duration-300"
              }
            >
              <Link
                href="https://github.com/Devmdmainuddin/"
                className="flex justify-between items-center w-full "
              >
                {" "}
                Github <Github size={22} className="secleup" />{" "}
              </Link>
            </li>
          </div>

          <div className=" fixed bottom-2 left-1/2 max-w-full -translate-x-1/2">
            <Dock className="items-end pb-3">
              {data.map((item, idx) => (
                <Link key={idx} href={item.href}>
                  <DockItem className="aspect-square rounded-full bg-gray-200 dark:bg-neutral-800">
                    <DockLabel>{item.title}</DockLabel>

                    <DockIcon className="secleup">{item.icon}</DockIcon>
                  </DockItem>
                </Link>
              ))}

              <DockItem className="aspect-square rounded-full bg-gray-200  dark:bg-neutral-800">
                <DockLabel>Theme</DockLabel>
                <DockIcon className="secleup flex justify-center items-center">
                  <ThemeSwitcher />
                </DockIcon>
              </DockItem>
            </Dock>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
